# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180521_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='joiner',
            field=models.ManyToManyField(related_name='users', to='app.User'),
        ),
    ]
