# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userfrinds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfrinds',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='userfrinds',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='users_friended', to='app.User'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='userfrinds',
        ),
    ]
